---
# These tasks installs the base system

- name: Install basic system utilities
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
   - acl
   - git
   - python-virtualenv
   - tmux
   - htop
   - python3
   - python3-dev
   - build-essential
